name: CDpr

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build-test-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: '8.0'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build and test with Gradle
        run: ./gradlew build

      - name: Publish package to GitHub Packages
        if: success()
        run: ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}